export enum AuditAction {
  TRANSACTION_CREDIT_SUCCESS = 'TRANSACTION_CREDIT_SUCCESS',
  TRANSACTION_DEBIT_SUCCESS = 'TRANSACTION_DEBIT_SUCCESS',
  TRANSACTION_DEBIT_FAILED = 'TRANSACTION_DEBIT_FAILED',
  TRANSACTION_DUPLICATE = 'TRANSACTION_DUPLICATE',
}
